/// Flutter icons MyNavBarIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyNavBarIcons
///      fonts:
///       - asset: fonts/MyNavBarIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyNavBarIcons {
  MyNavBarIcons._();

  static const _kFontFam = 'MyNavBarIcons';

  static const IconData settings = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData star_2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData calendar_2 = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData magnifying_glass_browser_copy = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData navdrawicon = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData paper_plane = const IconData(0xe807, fontFamily: _kFontFam);
}
